* build/apr_network.m4: In gethostbyname_r/gethostname_r checks, try harder   to suppress "unused variable" warnings which otherwise create false   negatives in the tests.
conftest.c:264:5: error: variable 'tmp' set but not used [-Werror=unused-but-set-variable]
  264 | int tmp = gethostbyname_r((const char *) 0, (struct hostent *) 0,