apr_skiplist: Handle ENOMEM from skiplisti_init(), fixing a compiler warning.
gcc-10 raises:
    tables/apr_skiplist.c: In function ‘apr_skiplist_add_index’:
    tables/apr_skiplist.c:284:16: error: ‘ni’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
      284 |         nsln = apr_skiplist_insert(ni, m->data);
          |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
because above skiplisti_init() might return with ENOMEM, leaving ni uninitialized.
Since apr_skiplist_add_index returns void, the only option is to abort() in
this case.

For apr_skiplist_init(), we can forward the APR_ENOMEM to the caller.


git-svn-id: https://svn.apache.org/repos/asf/apr/apr/trunk@1887481 13f79535-47bb-0310-9956-ffa450edef68