configure: Add bcrypt library for Windows target
bcrypt library is required for BCryptGenRandom function which is used
in misc/win32/rand.c file. This commit fixes the following linker error

misc/win32/rand.c:32:(.text+0x13): undefined reference to `BCryptGenRandom'

Signed-off-by: Biswapriyo Nath <nathbappai@gmail.com>