Merge r1887481, r1887482 from trunk:
apr_skiplist: Handle ENOMEM from skiplisti_init(), fixing a compiler warning.

gcc-10 raises:
    tables/apr_skiplist.c: In function ‘apr_skiplist_add_index’:
    tables/apr_skiplist.c:284:16: error: ‘ni’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
      284 |         nsln = apr_skiplist_insert(ni, m->data);
          |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
because above skiplisti_init() might return with ENOMEM, leaving ni uninitialized.
Since apr_skiplist_add_index returns void, the only option is to abort() in
this case.

For apr_skiplist_init(), we can forward the APR_ENOMEM to the caller.


Follow up to r1887481: fix skiplisti_init() returned pointer.


Submitted by: ylavic


git-svn-id: https://svn.apache.org/repos/asf/apr/apr/branches/1.7.x@1887486 13f79535-47bb-0310-9956-ffa450edef68