* build/apr_network.m4: In the gethostbyname_r/getservbyname_r checks,   try harder to suppress "unused variable" warnings which could   otherwise create false negatives in the tests.
conftest.c:264:5: error: variable 'tmp' set but not used [-Werror=unused-but-set-variable]
  264 | int tmp = gethostbyname_r((const char *) 0, (struct hostent *) 0,

GitHub: pr #68


git-svn-id: https://svn.apache.org/repos/asf/apr/apr/trunk@1927745 13f79535-47bb-0310-9956-ffa450edef68